# Generated by Django 4.1.7 on 2023-02-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Myuser",
            fields=[
                ("username", models.CharField(max_length=255, unique=True)),
                (
                    "email",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(name="Profile",),
    ]
