# Generated by Django 4.1.7 on 2023-02-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_myuser_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("college", models.CharField(max_length=255)),
                ("course", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("gender", models.CharField(max_length=255)),
            ],
        ),
    ]
