# Generated by Django 4.1.7 on 2023-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_userinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_table",
            fields=[
                ("username", models.CharField(max_length=255, unique=True)),
                (
                    "email",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=255)),
                ("college", models.CharField(max_length=255)),
                ("course", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("gender", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(name="Myuser",),
        migrations.DeleteModel(name="Userinfo",),
    ]
