# Generated by Django 4.1.7 on 2023-02-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_user_table_delete_myuser_delete_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_table",
            name="image",
            field=models.ImageField(default=1, upload_to="images"),
            preserve_default=False,
        ),
    ]
