# Generated by Django 4.1.7 on 2023-02-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_user_table_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_table",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
