# Generated by Django 4.1.7 on 2023-02-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_alter_user_table_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_table2",
            fields=[
                ("username", models.CharField(max_length=255, unique=True)),
                (
                    "email",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=255)),
                ("college", models.CharField(max_length=255)),
                ("course", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("gender", models.CharField(max_length=255)),
                ("images", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.DeleteModel(name="User_table",),
    ]
