# Generated by Django 4.1.7 on 2023-02-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0007_user_table2_delete_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_table2",
            name="images",
            field=models.ImageField(upload_to="templates2"),
        ),
    ]
