# Generated by Django 4.1.7 on 2023-02-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0008_alter_user_table2_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_table2",
            name="images",
            field=models.ImageField(upload_to="."),
        ),
    ]
