# Generated by Django 4.1.7 on 2023-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0010_alter_user_table2_email_alter_user_table2_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_table",
            fields=[
                ("username", models.CharField(max_length=255, unique=True)),
                (
                    "email",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("college", models.CharField(max_length=255)),
                ("course", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("gender", models.CharField(max_length=255)),
                ("images", models.ImageField(upload_to="images")),
                ("phone", models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.DeleteModel(name="User_table2",),
    ]
